version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      - MYSQL_ROOT_PASSWORD=api_pw
      - MYSQL_USER=api_user
      - MYSQL_DATABASE=api_db
      - MYSQL_PASSWORD=api_pw
    ports:
      - 3306:3306
    networks:
      - my_network
    volumes:
      - mysql_data:/var/lib/mysql 
      - ./api_db.sql:/docker-entrypoint-initdb.d/api_db.sql 

  api:
    build: ./API
    container_name: api-container
    ports:
      - 8000:8080
    networks:
      - my_network

networks:
  my_network:
    external: true

volumes:
  mysql_data: